version: "3.8"

services:
  mysql:
    build:
      context: .
      dockerfile: Dockerfile
    image: mysql:8.0
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ${DATA_PATH}:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - mysql-network
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin_container
    environment:
      PMA_HOST: mysql_container
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - "${PHPMYADMIN_PORT}:80"
    depends_on:
      - mysql
    networks:
      - mysql-network
    volumes:
      - ./docker/php/php.ini:/usr/local/etc/php/conf.d/php.ini

volumes:
  mysql-data:

networks:
  mysql-network:
    external: true
